<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNJoJljy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNJoJljy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNJoJljy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNJoJljy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNJoJljy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NJoJljy',
    'container.build_id' => 'd75e010e',
    'container.build_time' => 1588248307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNJoJljy');
